### PR TITLE
add luacheck, github actions, conf priv option, settingtypes.txt

### PR DESCRIPTION
**Pull request by wsor4035**
what the title says, basically maintenance, and adding a option to change the priv for no restrictions on mapfix.
would appreciate it if @SmallJoker and @Gael-de-Sailly could take a look at this

### CODE REVIEW

**Comment by gaelysam** [comment]
Hi, thank you for your contribution, but I'm not sure it's relevant to develop mapfix further. There is a similar built-in command in modern Minetest (`/fixlight here 20`) so the utility of mapfix now is pretty limited.

For the luacheck I don't see the interest for such a small piece of code. I think it it still easier to directly troubleshoot the code rather than to set up luacheck, and the future development of mapfix is probably a dead end.

I will review and merge at least your new privs code (remind me if I haven't done it in 1-2 days ;))

**Comment by wsor4035** [comment]
"Hi, thank you for your contribution, but I'm not sure it's relevant to develop mapfix further. There is a similar built-in command in modern Minetest (/fixlight here 20) so the utility of mapfix now is pretty limited."
id disagree, going to servers.minetest.net/list and searching for mapfix, 26 servers use it currently and i know a lot of people that use it in sp just for its simplicity.

"For the luacheck I don't see the interest for such a small piece of code. I think it it still easier to directly troubleshoot the code rather than to set up luacheck, and the future development of mapfix is probably a dead end."
its so simple, why not add it? it doesn't directly affect anything, more of a helpful hand

"I will review and merge at least your new privs code (remind me if I haven't done it in 1-2 days ;))"
sounds great

**Comment by wsor4035** [comment]
"I will review and merge at least your new privs code (remind me if I haven't done it in 1-2 days ;))"
@Gael-de-Sailly reminder ping

**Comment by gaelysam** [comment]
ok, merged the whole PR, thank you
> @Gael-de-Sailly reminder ping

yeah I totally knew I would forget ;)

**Pull request merged**
